# Generated by Django 5.2.11 on 2026-03-03 12:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rootcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcolor',
            name='color_hex',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
