# Generated by Django 5.2.11 on 2026-03-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='product_location',
        ),
        migrations.AddField(
            model_name='userdata',
            name='project_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
