# Generated by Django 5.2.11 on 2026-03-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_userdata_product_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='project_location',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='surname',
        ),
    ]
